[workspace]
resolver = "2"
members = [ "crates/*" ]

[workspace.dependencies]
anyhow = "1.0.93"
serde_json = "1.0.132"
serde = { version = "1.0.214", features = ["derive"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.20"
coarse-prof = "0.2.6"
# TODO: serious performance issues on serialization!
#bincode = "2.0.1"
bincode = "1.3.3"
build-info = "0.0.41"
build-info-build = "0.0.41"
thiserror = "2.0.17"
